#
#  needs .env file with:
#  - LOCAL_ADDRESS : the ip address of the docker host
#

version: '2'
services:

  zk:
    image: zookeeper:3.5
    restart: always

  pg:
    image: postgres:13
    environment:
    - POSTGRES_DB=chimera
    - POSTGRES_PASSWORD=let-me-in

  kafka:
    image: wurstmeister/kafka
    depends_on:
    - zk
    ports:
    - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_CREATE_TOPICS: billing:1:1
      KAFKA_ZOOKEEPER_CONNECT: zk:2181/kafka
      KAFKA_ADVERTISED_HOST_NAME: ${LOCAL_ADDRESS}
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock


  dcache:
    image: dcache/dcache:5.0
    depends_on:
    - pg
    - zk
    environment:
    - LOCALADDRESS=${LOCAL_ADDRESS}
    links:
    - pg:db-host
    - zk:zk-host
    - kafka:kafka-host
    ports:
    - "2049:2049"
    - "1094:1094"
    - "31094:31094"
    - "22224:22224"
    - "32049:32049"
    - "38080:38080"
    - "8080:8080"
    - "3880:3880"
    - "7771:7771"
    volumes:
    - ./docker-layout.conf:/opt/dcache/etc/layouts/docker-layout.conf
